# Generated by Django 4.2.8 on 2023-12-05 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('trx_type', models.IntegerField(choices=[(0, 'Top up'), (1, 'Buy')], verbose_name='Transaction type')),
                ('amount', models.IntegerField(help_text='RUB', verbose_name='Amount')),
                ('is_done', models.IntegerField(default=False, verbose_name='Is done')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('order_product', models.IntegerField(choices=[(0, '1 Day subscription'), (1, '7 Day subscription'), (2, '24 Day subscription')], verbose_name='Order product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.transaction', verbose_name='Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
