# Generated by Django 4.2.8 on 2023-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is done'),
        ),
    ]
