# Generated by Django 4.2.8 on 2023-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profiles/default.png', upload_to='', verbose_name='User avatar'),
        ),
    ]
