# Generated by Django 4.2.8 on 2023-12-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_until',
        ),
        migrations.AddField(
            model_name='user',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='Premium search counts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/', verbose_name='User avatar'),
        ),
    ]
