# Generated by Django 4.2.8 on 2023-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_subscription_until_user_search_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='search_count',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
