# Generated by Django 4.2.8 on 2023-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numer', models.CharField(max_length=20, unique=True, verbose_name='Phone number')),
                ('fullname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Fullname')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('inn', models.CharField(blank=True, max_length=128, null=True, verbose_name='INN')),
                ('driver_licence', models.CharField(blank=True, max_length=64, null=True, verbose_name='Driver licence')),
                ('possibles_addresses', models.CharField(blank=True, max_length=512, null=True, verbose_name='Possible addresses')),
                ('passport', models.CharField(blank=True, max_length=128, null=True, verbose_name='Passport')),
                ('insurance', models.CharField(blank=True, max_length=64, null=True, verbose_name='insurance')),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram username')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
