# Generated by Django 4.2.8 on 2023-12-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='driver_licence',
            new_name='driver_license',
        ),
    ]
