# Generated by Django 4.2.8 on 2023-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0002_rename_driver_licence_person_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Passport'),
        ),
    ]
