# Generated by Django 4.2.8 on 2023-12-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_base', '0003_alter_person_inn_alter_person_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.IntegerField(choices=[(0, 'Phone'), (1, 'Fullname + birthday')], verbose_name='Search type')),
                ('search_query', models.CharField(max_length=256, verbose_name='Search query')),
                ('status', models.IntegerField(choices=[(0, 'Phone'), (1, 'Fullname + birthday')], default=0, verbose_name='Status')),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search_base.person', verbose_name='Result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
