# Generated by Django 4.2.8 on 2023-12-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0004_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': 'Search history', 'verbose_name_plural': 'Search histories'},
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='search_base.person', verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'In progress'), (1, 'Not found'), (2, 'Success')], default=0, verbose_name='Status'),
        ),
    ]
