# Generated by Django 4.2.8 on 2023-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0005_alter_searchhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_query',
            field=models.JSONField(verbose_name='Search query'),
        ),
    ]
