# Generated by Django 4.2.8 on 2023-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0006_alter_searchhistory_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Search date'),
        ),
    ]
