# Generated by Django 4.2.8 on 2023-12-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0010_remove_searchhistory_search_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_query',
            field=models.JSONField(max_length=32, verbose_name='Search query'),
        ),
    ]
