# Generated by Django 4.2.8 on 2023-12-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_base', '0013_searchhistory_search_result_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
